name: default
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ubuntu_1804_full:
    name: Ubuntu 18.04 full
    env:
      cc: gcc-8
      cxx: g++-8
      cmake: -DCOMPILE_TESTS=on -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
      unittests: true
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -y \
          libgoogle-perftools-dev libprotobuf-dev protobuf-compiler \
          libboost-all-dev ${{ env.cc }} ${{ env.cxx }} ccache
    - name: Install MKL
      run: |-
        wget -qO- "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB" | sudo apt-key add -
        sudo sh -c "echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get install -y --no-install-recommends intel-mkl-64bit-2020.0-088
    - name: Generate ccache_vars for ccache based on machine
      shell: bash
      id: ccache_vars
      run: |-
        echo "::set-output name=hash::$(echo ${{ env.ccache_compilercheck }})"
        echo "::set-output name=timestamp::$(date '+%Y-%m-%dT%H.%M.%S')"
    - name: Cache-op for build-cache through ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.ccache_dir }}
        key: ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |-
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}
          ccache-${{ github.job }}
    - name: ccache environment setup
      run: |-
        echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
        echo "CCACHE_BASE_DIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=50M" >> $GITHUB_ENV
    - name: ccache prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry
    - name: cmake
      run: |-
        mkdir -p build
        cd build
        CC=${{ env.cc }} CXX=${{ env.cxx }} CUDAHOSTCXX=${{ env.cxx }} \
        cmake -L .. ${{ env.cmake }}
    - name: Build from source
      working-directory: build
      run: make -j2
    - name: ccache epilog
      run: 'ccache -s # Print current cache stats'
    - name: Print Versions
      working-directory: build
      run: ./app/bergamot-translator-app --version
    - name: Run unit tests
      working-directory: build
      run: make test
      if: ${{ ${{ env.unittests }} == 'true' }}
    - name: Install regression-test framework (BRT)
      working-directory: bergamot-translator-tests
      run: make install
    - name: Run regression-tests (BRT)
      working-directory: bergamot-translator-tests
      id: brt_run
      run: MARIAN=../build ./run_brt.sh ${{ env.brt_tags }}
      continue-on-error: true
    - name: Print logs of unsuccessful BRTs
      working-directory: bergamot-translator-tests
      run: grep "test*.sh" previous.log | cut -f '-' -d 2 | xargs -I% tail -n100 -v %
      if: ${{ steps.brt_run.outcome == 'failure' }}
    - name: Upload regression-tests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: brt-${{ github.job }}
        path: |-
          bergamot-translator-tests/**/*.expected
          bergamot-translator-tests/**/*.log
          bergamot-translator-tests/**/*.out
  ubuntu_1804_minimal:
    name: Ubuntu 18.04 minimal
    env:
      cc: gcc-8
      cxx: g++-8
      cmake: -DCOMPILE_TESTS=off -DUSE_WASM_COMPATIBLE_SOURCE=on -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
      brt_tags: "'#wasm'"
      unittests: false
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -y \
          libgoogle-perftools-dev libprotobuf-dev protobuf-compiler \
          libboost-all-dev ${{ env.cc }} ${{ env.cxx }} ccache
    - name: Install MKL
      run: |-
        wget -qO- "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB" | sudo apt-key add -
        sudo sh -c "echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get install -y --no-install-recommends intel-mkl-64bit-2020.0-088
    - name: Generate ccache_vars for ccache based on machine
      shell: bash
      id: ccache_vars
      run: |-
        echo "::set-output name=hash::$(echo ${{ env.ccache_compilercheck }})"
        echo "::set-output name=timestamp::$(date '+%Y-%m-%dT%H.%M.%S')"
    - name: Cache-op for build-cache through ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.ccache_dir }}
        key: ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |-
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}
          ccache-${{ github.job }}
    - name: ccache environment setup
      run: |-
        echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
        echo "CCACHE_BASE_DIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=50M" >> $GITHUB_ENV
    - name: ccache prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry
    - name: cmake
      run: |-
        mkdir -p build
        cd build
        CC=${{ env.cc }} CXX=${{ env.cxx }} CUDAHOSTCXX=${{ env.cxx }} \
        cmake -L .. ${{ env.cmake }}
    - name: Build from source
      working-directory: build
      run: make -j2
    - name: ccache epilog
      run: 'ccache -s # Print current cache stats'
    - name: Print Versions
      working-directory: build
      run: ./app/bergamot-translator-app --version
    - name: Run unit tests
      working-directory: build
      run: make test
      if: ${{ ${{ env.unittests }} == 'true' }}
    - name: Install regression-test framework (BRT)
      working-directory: bergamot-translator-tests
      run: make install
    - name: Run regression-tests (BRT)
      working-directory: bergamot-translator-tests
      id: brt_run
      run: MARIAN=../build ./run_brt.sh ${{ env.brt_tags }}
      continue-on-error: true
    - name: Print logs of unsuccessful BRTs
      working-directory: bergamot-translator-tests
      run: grep "test*.sh" previous.log | cut -f '-' -d 2 | xargs -I% tail -n100 -v %
      if: ${{ steps.brt_run.outcome == 'failure' }}
    - name: Upload regression-tests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: brt-${{ github.job }}
        path: |-
          bergamot-translator-tests/**/*.expected
          bergamot-translator-tests/**/*.log
          bergamot-translator-tests/**/*.out
  mac_full:
    name: MacOS full
    env:
      cmake: -DCOMPILE_TESTS=on -DUSE_APPLE_ACCELERATE=off -DUSE_FBGEMM=off -DUSE_STATIC_LIBS=off -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
      brt_tags: "'#mac'"
      unittests: true
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |-
        brew update
        brew install openblas protobuf coreutils ccache
    - name: Setup BLAS
      run: |-
        echo "LDFLAGS=-L/usr/local/opt/openblas/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/openblas/include" >> $GITHUB_ENV
    - name: Generate ccache_vars for ccache based on machine
      shell: bash
      id: ccache_vars
      run: |-
        echo "::set-output name=hash::$(echo ${{ env.ccache_compilercheck }})"
        echo "::set-output name=timestamp::$(date '+%Y-%m-%dT%H.%M.%S')"
    - name: Cache-op for build-cache through ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.ccache_dir }}
        key: ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |-
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}
          ccache-${{ github.job }}
    - name: ccache environment setup
      run: |-
        echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
        echo "CCACHE_BASE_DIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=50M" >> $GITHUB_ENV
    - name: ccache prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry
    - name: cmake
      run: |-
        mkdir -p build
        cd build
        cmake -L .. ${{ env.cmake }}
    - name: Build from source
      working-directory: build
      run: make -j2
    - name: ccache epilog
      run: 'ccache -s # Print current cache stats'
    - name: Print Versions
      working-directory: build
      run: ./app/bergamot-translator-app --version
    - name: Run unit tests
      working-directory: build
      run: make test
      if: ${{ ${{ env.unittests }} == 'true' }}
    - name: Install regression-test framework (BRT)
      working-directory: bergamot-translator-tests
      run: make install
    - name: Run regression-tests (BRT)
      working-directory: bergamot-translator-tests
      id: brt_run
      run: MARIAN=../build ./run_brt.sh ${{ env.brt_tags }}
      continue-on-error: true
    - name: Print logs of unsuccessful BRTs
      working-directory: bergamot-translator-tests
      run: grep "test*.sh" previous.log | cut -f '-' -d 2 | xargs -I% tail -n100 -v %
      if: ${{ steps.brt_run.outcome == 'failure' }}
    - name: Upload regression-tests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: brt-${{ github.job }}
        path: |-
          bergamot-translator-tests/**/*.expected
          bergamot-translator-tests/**/*.log
          bergamot-translator-tests/**/*.out
  mac_minimal:
    name: MacOS minimal
    env:
      cmake: -DCOMPILE_TESTS=off -DUSE_APPLE_ACCELERATE=off -DUSE_FBGEMM=off -DUSE_STATIC_LIBS=on -DUSE_WASM_COMPATIBLE_SOURCE=on -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
      brt_tags: "'#wasm'"
      unittests: false
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |-
        brew update
        brew install openblas protobuf coreutils ccache
    - name: Setup BLAS
      run: |-
        echo "LDFLAGS=-L/usr/local/opt/openblas/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/openblas/include" >> $GITHUB_ENV
    - name: Generate ccache_vars for ccache based on machine
      shell: bash
      id: ccache_vars
      run: |-
        echo "::set-output name=hash::$(echo ${{ env.ccache_compilercheck }})"
        echo "::set-output name=timestamp::$(date '+%Y-%m-%dT%H.%M.%S')"
    - name: Cache-op for build-cache through ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.ccache_dir }}
        key: ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |-
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
          ccache-${{ github.job }}-${{ steps.ccache_vars.outputs.hash }}
          ccache-${{ github.job }}
    - name: ccache environment setup
      run: |-
        echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
        echo "CCACHE_BASE_DIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=50M" >> $GITHUB_ENV
    - name: ccache prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry
    - name: cmake
      run: |-
        mkdir -p build
        cd build
        cmake -L .. ${{ env.cmake }}
    - name: Build from source
      working-directory: build
      run: make -j2
    - name: ccache epilog
      run: 'ccache -s # Print current cache stats'
    - name: Print Versions
      working-directory: build
      run: ./app/bergamot-translator-app --version
    - name: Run unit tests
      working-directory: build
      run: make test
      if: ${{ ${{ env.unittests }} == 'true' }}
    - name: Install regression-test framework (BRT)
      working-directory: bergamot-translator-tests
      run: make install
    - name: Run regression-tests (BRT)
      working-directory: bergamot-translator-tests
      id: brt_run
      run: MARIAN=../build ./run_brt.sh ${{ env.brt_tags }}
      continue-on-error: true
    - name: Print logs of unsuccessful BRTs
      working-directory: bergamot-translator-tests
      run: grep "test*.sh" previous.log | cut -f '-' -d 2 | xargs -I% tail -n100 -v %
      if: ${{ steps.brt_run.outcome == 'failure' }}
    - name: Upload regression-tests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: brt-${{ github.job }}
        path: |-
          bergamot-translator-tests/**/*.expected
          bergamot-translator-tests/**/*.log
          bergamot-translator-tests/**/*.out

