name: default
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  cached:
    name: cached
    env:
      gcc: 8
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      cache_cmd: "bash ${GITHUB_WORKSPACE}/scripts/ci/compiler-hash.sh %compiler%"
      cmake: "-DCMAKE_BUILD_TYPE=Release -DCOMPILE_TESTS=on -DCOMPILE_SERVER=off"
      brt_tags: "'#native'"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -y \
          libgoogle-perftools-dev libprotobuf-dev protobuf-compiler \
          libboost-all-dev g++-${{ env.gcc }} ccache
    - name: Install MKL
      run: |-
        wget -qO- "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB" | sudo apt-key add -
        sudo sh -c "echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get install -y --no-install-recommends intel-mkl-64bit-2020.0-088
    - name: Cache-op for build-cache through ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ matrix.name }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |-
          ccache-${{ matrix.name }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-
          ccache-${{ matrix.name }}-${{ steps.ccache_vars.outputs.hash }}-
          ccache-${{ matrix.name }}-
    - name: Generate ccache_vars for ccache based on machine
      shell: bash
      id: ccache_vars
      run: |-
        echo "::set-output name=hash::$(${{ env.cache_cmd }})
        echo "::set-output name=timestamp::$(date '+%Y-%m-%dT%H.%M.%S')
    - name: ccache environment setup
      run: |-
        echo "CCACHE_COMPILER_CHECK=${{ env.cache_cmd }}" >> $GITHUB_ENV
        echo "CCACHE_BASE_DIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=100M" >> $GITHUB_ENV
    - name: ccache prolog
      run: |-
        ccache -s # Print current cache stats
        ccache -z # Zero cache entry
    - name: cmake
      run: |-
        mkdir -p build
        cd build
        CC=/usr/bin/gcc-${{ env.gcc }} CXX=/usr/bin/g++-${{ env.gcc }} CUDAHOSTCXX=/usr/bin/g++-${{ env.gcc }} \
        cmake -L .. \
          ${{ env.cmake }}
    - name: Build from source
      working-directory: build
      run: make -j2
    - name: ccache epilog
      run: 'ccache -s # Print current cache stats'
    - name: Print Versions
      working-directory: build
      run: ./app/bergamot-translator-app --version
    - name: Run unit tests
      working-directory: build
      run: make test
    - name: Install regression-test framework (BRT)
      working-directory: bergamot-translator-tests
      run: make install
    - name: Run regression-tests (BRT)
      working-directory: bergamot-translator-tests
      run: MARIAN=../build ./run_brt.sh ${{ env.brt_tags }}
  fresh:
    name: fresh
    env:
      gcc: 8
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      cache_cmd: "bash ${GITHUB_WORKSPACE}/scripts/ci/compiler-hash.sh %compiler%"
      cmake: "-DCMAKE_BUILD_TYPE=Release -DCOMPILE_TESTS=on -DCOMPILE_SERVER=off"
      brt_tags: "'#native'"
    needs: cached
    runs-on: ubuntu-18.04
    if: ${{ needs.cached.result == 'failure' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |-
        sudo apt-get update
        sudo apt-get install -y \
          libgoogle-perftools-dev libprotobuf-dev protobuf-compiler \
          libboost-all-dev g++-${{ env.gcc }} ccache
    - name: Install MKL
      run: |-
        wget -qO- "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB" | sudo apt-key add -
        sudo sh -c "echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/intel-mkl.list"
        sudo apt-get install -y --no-install-recommends intel-mkl-64bit-2020.0-088
    - name: cmake
      run: |-
        mkdir -p build
        cd build
        CC=/usr/bin/gcc-${{ env.gcc }} CXX=/usr/bin/g++-${{ env.gcc }} CUDAHOSTCXX=/usr/bin/g++-${{ env.gcc }} \
        cmake -L .. \
          ${{ env.cmake }}
    - name: Build from source
      working-directory: build
      run: make -j2
    - name: Print Versions
      working-directory: build
      run: ./app/bergamot-translator-app --version
    - name: Run unit tests
      working-directory: build
      run: make test
    - name: Install regression-test framework (BRT)
      working-directory: bergamot-translator-tests
      run: make install
    - name: Run regression-tests (BRT)
      working-directory: bergamot-translator-tests
      run: MARIAN=../build ./run_brt.sh ${{ env.brt_tags }}

